### PR TITLE
NewResourceName: AdcsTemplate. Add and remove CA Templates on an Enterprise CA

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR adds a new resource named AdcsTemplate. This resource can be used to add/remove
templates on an Enterprise Certificate Authority.

The resource uses the `Get-CATemplate`, `Add-CATemplate` and `Remove-CATemplate` cmdlets from the ADCSAdministration PowerShell Module. 

#### This Pull Request (PR) fixes the following issues

#86 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/activedirectorycsdsc/85)

### CODE REVIEW

**Comment by PlagueHO** [comment]
I'll get onto the review this weekend. Haven't had much time lately.

**Comment by X-Guardian** [comment]
Hi, just checking this PR hasn't been forgotten about...

**Comment by PlagueHO** [comment]
Sorry @X-Guardian - I've been really far behind lately. I haven't forgotten though - just working through the backlog of reviews I've got as much as I can. I'll be doing some tonight.

**Comment by X-Guardian** [comment]
Cheers @PlagueHO. I'll still do an integration test for this if you can point me at a good example of one.

**Comment by PlagueHO** [comment]
There isn't a perfect example as we can't run these integration tests in AppVeyor because we just can't make an Enterprise CA (can't domain join it). But we can use a pattern like this: https://github.com/PowerShell/DFSDsc/blob/dev/Tests/Integration/MSFT_DFSNamespaceFolder.Integration.Tests.ps1

This will execute tests only if the specific conditions are met (e.g. an ADCS Enterprise CA is installed).

**Pull request merged**
