### PR TITLE
BREAKING CHANGE: Rename module to ActiveDirectoryCSDsc - Fixes #38

### LINKED ISSUE #38: Convert Module Name to ActiveDirectoryCSDsc
As per recent DSC Resource Naming guidelines changes:
https://github.com/PowerShell/DscResources/blob/master/Naming.md

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR implements the changes that enable renaming the module to ActiveDirectoryCSDsc.

**This Pull Request (PR) fixes the following issues:**
#38 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju - would you be able to review this? I've followed the procedure you outlined to me and it is looking good. I've renamed my fork and the tests pass: https://ci.appveyor.com/project/PlagueHO/adcsdeploymentdsc

@kwirkykat - can you please rename this repo if you're happy and I'll get this PR merged?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xadcsdeployment/41)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[AdcsDeploymentDsc.psd1, line 3 at r1](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-L17H4WBCK0zP5RahEtG:-L17H4WBCK0zP5RahEtH:blim10z) ([raw file](https://github.com/powershell/xadcsdeployment/blob/e84e660277fe1f5b88e1958a017d29cb771ec65f/AdcsDeploymentDsc.psd1#L3)):*
> ```PowerShell
> @{
>     # Version number of this module.
>     ModuleVersion = '2.0.0.0'
> ```

Katie changes this upon release.

---

*[AdcsDeploymentDsc.psd1, line 51 at r1](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-L17HCtQS_NhSdOSsU50:-L17HCtQS_NhSdOSsU51:b4b2cr) ([raw file](https://github.com/powershell/xadcsdeployment/blob/e84e660277fe1f5b88e1958a017d29cb771ec65f/AdcsDeploymentDsc.psd1#L51)):*
> ```PowerShell
>             # ReleaseNotes of this module
>         ReleaseNotes = '- AdcsCertificateAuthority: CertFilePassword invalid type - fixes
>   [issue 36](https://github.com/PowerShell/AdcsDeploymentDsc/issues/36)
> ```

Let's leave this untouched as Katie will change this upon release.

---

*[README.md, line 179 at r1](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-L17IP8MRKRAcxp1hK-Q:-L17IP8MRKRAcxp1hK-R:b-n9f0g6) ([raw file](https://github.com/powershell/xadcsdeployment/blob/e84e660277fe1f5b88e1958a017d29cb771ec65f/README.md#L179)):*
> ```Markdown
> - BREAKING CHANGE: Renamed module to AdcsDeploymentDsc.
> 
> ### 1.4.0.0
> ```

Non-blocking: We left the history untouched in SqlServerDsc - using old xSQLServer naming. Only the Unreleased section was updated to new URL and names. It seems that old URL's will resolve correctly, so nothing broke. And seemed wrong to update the history, since old versions of the module can be downloaded with the old names and unchanged history. 
Non-blocking as this is up to you, just thought I should mention it. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Examples/Resources/xAdcsCertificationAuthority/1-InstallCertificationAthority.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-L17MowAUglh2bemoG0q:-L17MowAUglh2bemoG0r:btxbehd) ([raw file](https://github.com/powershell/xadcsdeployment/blob/e84e660277fe1f5b88e1958a017d29cb771ec65f/Examples/Resources/xAdcsCertificationAuthority/1-InstallCertificationAthority.ps1#L1)):*
> ```PowerShell
> <#
> ```

The folder is not renamed here.

I see duplicate folders? https://github.com/PlagueHO/AdcsDeploymentDsc/tree/Issue-38/Examples/Resources

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41)*

**Comment by PlagueHO** [comment]
Review status: 21 of 27 files reviewed at latest revision, 4 unresolved discussions.

---

*[AdcsDeploymentDsc.psd1, line 3 at r1](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-L17H4WBCK0zP5RahEtG:-L18vcKu_qWimjO_VGqg:boqkhcz) ([raw file](https://github.com/powershell/xadcsdeployment/blob/e84e660277fe1f5b88e1958a017d29cb771ec65f/AdcsDeploymentDsc.psd1#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Katie changes this upon release.
</blockquote></details>

Doh! I changed this when I was investigating something - forgot to change it back. Reverted back now.

---

*[AdcsDeploymentDsc.psd1, line 51 at r1](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-L17HCtQS_NhSdOSsU50:-L18w7S-YzaN5YvsADnm:b-896fix) ([raw file](https://github.com/powershell/xadcsdeployment/blob/e84e660277fe1f5b88e1958a017d29cb771ec65f/AdcsDeploymentDsc.psd1#L51)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Let's leave this untouched as Katie will change this upon release.
</blockquote></details>

Done.

---

*[README.md, line 179 at r1](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-L17IP8MRKRAcxp1hK-Q:-L18wQLyC3-vdBplXQ7x:b-4wqh66) ([raw file](https://github.com/powershell/xadcsdeployment/blob/e84e660277fe1f5b88e1958a017d29cb771ec65f/README.md#L179)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking: We left the history untouched in SqlServerDsc - using old xSQLServer naming. Only the Unreleased section was updated to new URL and names. It seems that old URL's will resolve correctly, so nothing broke. And seemed wrong to update the history, since old versions of the module can be downloaded with the old names and unchanged history. 
Non-blocking as this is up to you, just thought I should mention it. :)
</blockquote></details>

I have reverted all this :grin: Now that I know I'll repeat the process for the other repos as I change them.

---

*[Examples/Resources/xAdcsCertificationAuthority/1-InstallCertificationAthority.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-L17MowAUglh2bemoG0q:-L18w_zaLONv9Q3Uqevw:b-qplwlb) ([raw file](https://github.com/powershell/xadcsdeployment/blob/e84e660277fe1f5b88e1958a017d29cb771ec65f/Examples/Resources/xAdcsCertificationAuthority/1-InstallCertificationAthority.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The folder is not renamed here.

I see duplicate folders? https://github.com/PlagueHO/AdcsDeploymentDsc/tree/Issue-38/Examples/Resources
</blockquote></details>

Not sure what happened here... but the duplicates are gone now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41)*

**Comment by PlagueHO** [comment]
Should be good to go now @johlu

---

Review status: 21 of 27 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-:-L18wkSDUYa6cp35ucad:b6xtvrr)*

**Comment by johlju** [comment]
Reviewed 1 of 44 files at r1, 6 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 177 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-L19CgGRbRKnNRBwPyT3:-L19CgGSI_FajulyS_n4:bk5i0pv) ([raw file](https://github.com/powershell/xadcsdeployment/blob/d07e2e6d25a0a677d894b2c483d2438db2a68e9d/README.md#L177)):*
> AdcsDeploymentDsc

This is non-blocking: Question: Why AdcsDeploymentDsc and not AdcsDsc, or ActiveDirectoryCSDsc (ActiveDirectoryCertificateServicesDsc would be to long) to align with the future ActiveDirectoryDsc, or AdcsConfigurationDsc . I'm all good with AdcsDeploymentDsc as the name, just thought I would raise the question, since this is the time to make this kind of change.

---

*[Examples/Resources/xAdcsCertificationAuthority/1-InstallCertificationAthority.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-L17MowAUglh2bemoG0q:-L19E6Dx2iiOIZCbAm9y:b3xxtbj) ([raw file](https://github.com/powershell/xadcsdeployment/blob/e84e660277fe1f5b88e1958a017d29cb771ec65f/Examples/Resources/xAdcsCertificationAuthority/1-InstallCertificationAthority.ps1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Not sure what happened here... but the duplicates are gone now.
</blockquote></details>

Could not acknowledge this one (missing the word 'Done').

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 177 at r2](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-L19CgGRbRKnNRBwPyT3:-L1Aarh3HdwGBsQ5poN5:bk5y238) ([raw file](https://github.com/powershell/xadcsdeployment/blob/d07e2e6d25a0a677d894b2c483d2438db2a68e9d/README.md#L177)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> AdcsDeploymentDsc

This is non-blocking: Question: Why AdcsDeploymentDsc and not AdcsDsc, or ActiveDirectoryCSDsc (ActiveDirectoryCertificateServicesDsc would be to long) to align with the future ActiveDirectoryDsc, or AdcsConfigurationDsc . I'm all good with AdcsDeploymentDsc as the name, just thought I would raise the question, since this is the time to make this kind of change.
</blockquote></details>

Good call. I'm not adverse to selecting a different name here at all. I'd think ActiveDirectoryCSDsc might be the better name as one day we might actually have a ADCS resource that isn't specifically deployment related (e.g. such as the CA configuration one I proposed a couple of years back).

My vote would be with ActiveDirectoryCSDsc - @kwirkykat - do you have any preference here at all?

---

*[Examples/Resources/xAdcsCertificationAuthority/1-InstallCertificationAthority.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-L17MowAUglh2bemoG0q:-L1AbFQ_qesfMU7aKxj5:bh6jc2d) ([raw file](https://github.com/powershell/xadcsdeployment/blob/e84e660277fe1f5b88e1958a017d29cb771ec65f/Examples/Resources/xAdcsCertificationAuthority/1-InstallCertificationAthority.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could not acknowledge this one (missing the word 'Done').
</blockquote></details>

Can you just set this to "Satisfied" by selecting the tick on the right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41)*

**Comment by johlju** [comment]
:lgtm:

@kwirkykat and @PlagueHO just one outstanding question, the name of the resource (see review comments).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xadcsdeployment/41#-:-L1BneUtfn5lx2g8rezt:b-y8wva6)*

**Comment by PlagueHO** [comment]
@kwirkykat, @mgreenegit  - do either of you have any preference or suggestion for the name of this resource when moving out of HQRM? Options:
1. AdcsDeploymentDsc - default, but isn't clear that it is related to Active Directory and I'd always hoped this resource could be extended to do more than deploy CS components but also configure them.
2. ActiveDirectoryCSDsc - aligns well with future ActiveDirectoryDsc
3. AdcsConfigurationDsc - Not my preference but thought I'd throw it in?
4. Something else?

Personally I'm leaning towards 2, but I'd love to get your preference as I'd like to get this one converted over so I can start moving onto the next ones.

**Comment by kwirkykat** [comment]
@PlagueHO I like either ActiveDirectoryCSDsc or ADCertificateServicesDsc.
@mgreenegit Preferences?

**Comment by PlagueHO** [comment]
@kwirkykat - in the absence of a weigh-in from @mgreenegit I reckon we go with `ActiveDirectoryCSDsc`. So I'll make this happen.

**Comment by PlagueHO** [comment]
I'm going to close this PR and create a new one as there seems to be something going wrong with the AppVeyor after doing the second change.

**Comment by PlagueHO** [comment]
This process has messed up somewhere, so I'm going to close this PR and create a new one.

**Comment by PlagueHO** [comment]
@kwirkykat, @mbreakey3 - can either of you rename this Repo to `ActiveDirectoryCSDsc` for me? This should allow the tests to then pass in the PR.

**Comment by kwirkykat** [comment]
@PlagueHO Done. Re-triggering tests.

**Comment by PlagueHO** [comment]
Thanks @kwirkykat  - do you have any idea what is going on here with the tests? It looks like the AppVeyor definition is still using the old project name: 
https://ci.appveyor.com/project/PowerShell/xadcsdeployment/build/1.1.136.0#L2

Is it possible that the AppVeyor build has the project clone path hard coded into the AppVeyor settings?

E.g.
image

Otherwise I'm stumped as to where the incorrect path is coming from. @johlju - any ideas?

**Comment by johlju** [comment]
@PlagueHO  I see it says `C:\projects\xadcsdeployment` in the Console log, that wasn't a problem in SqlServerDsc. It's most likely the AppVeyor configuration for that particular repo.

**Comment by kwirkykat** [comment]
Closing and re-opening PR to get it to hook up to new AppVeyor project

**Comment by kwirkykat** [comment]
@PlagueHO @johlju Should work now.
For SqlServerDsc I just made a new AppVeyor project with the renamed repo.
This time I tried renaming the xAdcsDeployment project so we could keep the history, but it looks like even when I rename everything in the settings, the AppVeyor URL for the project still had xAdcsDeployment in it with no way to change that.
So now I just made a new project for this repo too, and it seems to be working now.

**Comment by PlagueHO** [comment]
Thank you so much @KwirkyKat - very much appreciated. @johlju - would you mind checking over this one so I can complete the merge?

---

Review status: 12 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/activedirectorycsdsc/41#-:-L8BHvj0FQXjQ8MvhVGG:b9qh8h9)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 10 of 45 files at r1, 17 of 18 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/activedirectorycsdsc/41#-:-L8CY-r4LPAzhJx-ln4F:bnfp4nl)*

**Pull request merged**
