### PR TITLE
Added EnrollmentPolicyWebService resource - Fixes #43

### LINKED ISSUE #43: xAdcsCertificateAuthority - Add Certificate Enrollment Policy Web service configuration
The module is missing configuration of the Certificate Enrollment Policy Web service.

There is a cmdlet in ADCS 2012 R2 & newer to configure the web service - https://docs.microsoft.com/en-us/powershell/module/adcsdeployment/install-adcsenrollmentpolicywebservice?view=win10-ps

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Added new resource EnrollmentPolicyWebService.

**This Pull Request (PR) fixes the following issues:**
- Changed `Assert-VerifiableMocks` to be `Assert-VerifiableMock` to meet
  Pester standards.
- Updated license year in LICENSE.MD and module manifest to 2018.
- Removed requirement for Pester maximum version 4.0.8.
- Added new resource EnrollmentPolicyWebService - see
  [issue #43](https://github.com/PowerShell/ActiveDirectoryCSDsc/issues/43).

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju - would you mind reviewing if you get a chance?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO Will do tomorrow! :)

**Comment by PlagueHO** [comment]
Should be ready to go @johlju!

---

Review status: 7 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[DSCResources/MSFT_AdcsEnrollmentPolicyWebService/MSFT_AdcsEnrollmentPolicyWebService.psm1, line 72 at r1](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49#-LDfBVnB3y1DaQzPxJGy:-LDp2hU71P9wRjS-yPZK:b-896fix) ([raw file](https://github.com/powershell/activedirectorycsdsc/blob/56114c649cf204befe4c609f3a9b5a270a233d90/DSCResources/MSFT_AdcsEnrollmentPolicyWebService/MSFT_AdcsEnrollmentPolicyWebService.psm1#L72)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should not be need this parameter in the Get-TargetResource?
</blockquote></details>

Done.

---

*[DSCResources/MSFT_AdcsEnrollmentPolicyWebService/MSFT_AdcsEnrollmentPolicyWebService.psm1, line 83 at r1](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49#-LDfBeoy8lXs4K0tT3Pb:-LDp2iA5BZGMs09K8Mrp:b-896fix) ([raw file](https://github.com/powershell/activedirectorycsdsc/blob/56114c649cf204befe4c609f3a9b5a270a233d90/DSCResources/MSFT_AdcsEnrollmentPolicyWebService/MSFT_AdcsEnrollmentPolicyWebService.psm1#L83)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

we never set `$Ensure` to `'Present'`?
</blockquote></details>

Done.

---

*[DSCResources/MSFT_AdcsEnrollmentPolicyWebService/MSFT_AdcsEnrollmentPolicyWebService.psm1, line 92 at r1](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49#-LDfBJQW4PPkk9mElWGT:-LDp2jJh2ubqepeHS9wz:bd9chs0) ([raw file](https://github.com/powershell/activedirectorycsdsc/blob/56114c649cf204befe4c609f3a9b5a270a233d90/DSCResources/MSFT_AdcsEnrollmentPolicyWebService/MSFT_AdcsEnrollmentPolicyWebService.psm1#L92)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Why do we always set this to `$null`?
</blockquote></details>

A mistake. Done.

---

*[DSCResources/MSFT_AdcsEnrollmentPolicyWebService/MSFT_AdcsEnrollmentPolicyWebService.psm1, line 176 at r1](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49#-LDf2JzH97u-DY83Cp4-:-LDp2qv672fAzbcbCxk5:b-fcdb36) ([raw file](https://github.com/powershell/activedirectorycsdsc/blob/56114c649cf204befe4c609f3a9b5a270a233d90/DSCResources/MSFT_AdcsEnrollmentPolicyWebService/MSFT_AdcsEnrollmentPolicyWebService.psm1#L176)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $KeyBasedRenewal
> ```

If `KeyBasedRenewal` was $false, and the it set to $true on a second run, will this row install the `"KeyBasedRenewal_ADPolicyProvider_CEP_$webAppAutenticationType"` and remove the other? or is this scenario something that cannot be supported?

If it can not install that, then the configuration will always fail? :thinking: 

(testing the Discussion disposition for this comment)
</blockquote></details>

There is no logic built into the MSFT cmdlets to prevent the installation of both KeyBasedRenewal and non-KeyBasedRenewal Web Apps for each Authorization Type. Therefore I think the DSC resource needs to support this also. I can see why someone might want to do this as well: different appliances might have different requirements and so you wouldn't want to have two different policy servers to support each policy.

---

*[DSCResources/MSFT_AdcsEnrollmentPolicyWebService/MSFT_AdcsEnrollmentPolicyWebService.psm1, line 395 at r1](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49#-LDez_mk4kNM6otKRoQn:-LDp40XWBHnW53Nga97Y:bxt7tix) ([raw file](https://github.com/powershell/activedirectorycsdsc/blob/56114c649cf204befe4c609f3a9b5a270a233d90/DSCResources/MSFT_AdcsEnrollmentPolicyWebService/MSFT_AdcsEnrollmentPolicyWebService.psm1#L395)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ($_.PhysicalPath -split '\\')[-1]
> ```

Non-blocking (trying the new "Informing"): This does work, but wouldn't `Split-Path -Path $_.PhysicalPath -Leaf` be better since we working with paths? 
</blockquote></details>

Informing seems to work. Done :grin:

---

*[DSCResources/MSFT_AdcsEnrollmentPolicyWebService/MSFT_AdcsEnrollmentPolicyWebService.schema.mof, line 5 at r1](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49#-LDewvZV7NshqnBFDF2L:-LDp4MH0Dceoqq0mnjCz:b-cspf3a) ([raw file](https://github.com/powershell/activedirectorycsdsc/blob/56114c649cf204befe4c609f3a9b5a270a233d90/DSCResources/MSFT_AdcsEnrollmentPolicyWebService/MSFT_AdcsEnrollmentPolicyWebService.schema.mof#L5)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> SSLCertThumbprint
> ```

`SslCertThumbprint` (lower-case 'sl'). Throughout.

Although, wouldn't `CertificateThumbprint`, or just `Thumbprint`, be better? Isn't "SSL" implicit anyway?
</blockquote></details>

Done.

Although I think we should leave it as SslCertThumbprint as this is what the MSFT cmdlets use which aligns with the documentation from MSFT and also simplifies the DSC Resource code a lot (otherwise we have to remap the parameter when using the splats).

---

*[Tests/Unit/MSFT_AdcsEnrollmentPolicyWebService.Tests.ps1, line 46 at r1](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49#-LDf6I_nEneOKMg69rwg:-LDp5KuWAO7RtFq287IX:b-896fix) ([raw file](https://github.com/powershell/activedirectorycsdsc/blob/56114c649cf204befe4c609f3a9b5a270a233d90/Tests/Unit/MSFT_AdcsEnrollmentPolicyWebService.Tests.ps1#L46)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> "Administrator"
> ```

Single quotes
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_AdcsEnrollmentPolicyWebService.Tests.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49#-LDf4NlgBKHRnqy4RjhM:-LDp4tDe3kZqLOH8siim:bz8q70b) ([raw file](https://github.com/powershell/activedirectorycsdsc/blob/56114c649cf204befe4c609f3a9b5a270a233d90/Tests/Integration/MSFT_AdcsEnrollmentPolicyWebService.Tests.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This file should be named `Integration.Tests.ps1`.
</blockquote></details>

Done.

Also corrected the name of the other integration test file.

---

*[Tests/Integration/MSFT_AdcsEnrollmentPolicyWebService.Tests.ps1, line 43 at r1](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49#-LDf5NrP-OgcHFbCAyQ_:-LDp62Y2B6JdmZvORVvi:b-896fix) ([raw file](https://github.com/powershell/activedirectorycsdsc/blob/56114c649cf204befe4c609f3a9b5a270a233d90/Tests/Integration/MSFT_AdcsEnrollmentPolicyWebService.Tests.ps1#L43)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe we could write out the next warning as well (if $true) before returning? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49#-:-LDpAFOP7UMQPlhNA6Yg:b-4gx61a)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49#-:-LDpImA7-rfyuyhT5MD7:bnfp4nl)*

**Comment by johlju** [comment]
Awesome work on this one! Must have take a while to put this together! 😃

**Comment by PlagueHO** [comment]
Thank you @johlju - it did take a bit longer than expected (I spent ages trying to get it to work on a non-domain joined server - only to find out it isn't supported :grin:).

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/activedirectorycsdsc/49#-:-LDuEboSCSsbZglNl8io:be4vyhi)*

**Comment by johlju** [comment]
I know the feeling - going down the rabbit hole only to find out it's blocked. 😆

**Pull request merged**
